---
version: 3.8.0
name: "Zen Developer: Freelance Full Stack Developer"
description: "Zen Developer: Official blog of Freelance Full Stack Developer Rodrigo Aguila. PHP, MySQLi, Ruby on Rails, HTML5/CSS3, JS, Bootstrap, WordPress, Jekyll and more about technology and development..."
repository: https://github.com/jekyll/jekyll
timezone: America/Santiago
twitter:
  username: budowebs
logo: "/img/logo-2x.png"
google_analytics_id: UA-50755011-1
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/:year/:month/:day/:title/"
    output: true
  tutorials:
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
    image: "/img/twitter-card.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji
sass:
  style: compressed
exclude:
- ".gitignore"
- CNAME
- icomoon-selection.json
- readme.md
